### ISSUE TITLE
出错了大兄弟 ：

### ISSUE THREAD

**Issue by CherishNA** [kxg3030/shermie-proxy#1]
出错了大兄弟 ：
`Core\ProxyHttp.go:226:33: sslConn.ReadLastTimeBytes undefined (type *tls.Conn has no field or method ReadLastTimeBytes)`

**Comment by kxg3030** [comment]
把这个方法加到你的gopath目录下src/crypto/tls/conn.go文件中
`
func (c *Conn) ReadLastTimeBytes() []byte {
	return c.rawInput.Bytes()
}
`
