### ISSUE TITLE
在OnHttpRequestEvent中修给POST的请求参数没有任何作用,服务器后台接收到的还是未修改的数据!

### ISSUE THREAD

**Issue by 592530326** [kxg3030/shermie-proxy#11]

**Comment by kxg3030** [comment]
可以贴一下代码，修改数据以后还是要调用resolve的

**Comment by 592530326** [comment]
i.request = i.SetRequest(i.request)
	//body, _ := i.ReadBody(i.request.Body)
	//i.request.Body = io.NopCloser(bytes.NewReader(body))
	i.server.OnHttpRequestEvent(i.request)
	body, _ := i.ReadBody(i.request.Body)
	i.request.Header.Set("Content-Length", strconv.Itoa(len(body)))
	i.request.ContentLength = int64(len(body))
	i.request.Body = io.NopCloser(bytes.NewReader(body)) 这是我修改后的代码,你和你之前的代码比较看看

**Comment by kxg3030** [comment]
你需要在回调里面调用resolve(message)，将你修改后的数据或者原始数据传入，不需要修改代码的，你可以加群，沟通方便一些

**Comment by 592530326** [comment]
好的,我看到您这边已经更新了代码!

**Comment by kxg3030** [comment]
如果没有其他问题，我就关闭issue了
