### ISSUE TITLE
升级ws协议失败：websocket: not a websocket handshake: 'Sec-WebSocket-Key' header is missing or blank

### ISSUE THREAD

**Issue by 1nformation** [kxg3030/shermie-proxy#17]
升级ws协议失败：websocket: not a websocket handshake: 'Sec-WebSocket-Key' header is missing or blank ；但是自己用抓包工具看协议头是有这个Sec-WebSocket-Key的

**Comment by kxg3030** [comment]
有测试连接地址吗，没有的话群里私聊我
