### ISSUE TITLE
代理返回响应数据失败

### ISSUE THREAD

**Issue by Huang-Jacky** [kxg3030/shermie-proxy#2]
![image](https://user-images.githubusercontent.com/9347008/187039130-ae204e36-257d-43f7-9e90-8db5163020da.png)

**Comment by kxg3030** [comment]
你只贴一张图，很难帮到你

**Comment by Huang-Jacky** [comment]
> 你只贴一张图，很难帮到你

go version go1.19 darwin/arm64

我使用代理抓移动应用的数据，
工程内证书 cert.crt 已安装到设备
在启动代理以后， 移动应用内有些数据可以正常的解析出来，但很多数据都是如图片所示的响应失败

所以想了解下是我有什么地方没有用对吗？

**Comment by kxg3030** [comment]
你可以打印一下 响应失败的时候 request对象里面的请求地址  应该是你客户端连接被主动关闭了  服务器写入数据的时候 报错
