### ISSUE TITLE
讲讲原理

### ISSUE THREAD

**Issue by niaiwomattt** [kxg3030/shermie-proxy#5]
希望能讲讲原理，怎么实现抓包的？我大概看了一下源码，就是实现了代理转发服务，怎么实现把链路中的数据抓包出来呢？

**Comment by kxg3030** [comment]
这个只是一个代理服务 只能让软件指定代理到这个应用监听的端口 并没有自动监听系统请求的功能哈

**Comment by niaiwomattt** [comment]
哦哦，我看你在 https://learnku.com/articles/69287 写的文章，我以为是抓包工具呢！

**Comment by kxg3030** [comment]
这没有明显的接线  这个可以认为是抓包工具 只是常见的抓包工具 自动设置了系统的代理而已
