### ISSUE TITLE
这个库很牛逼,我很喜欢,但是存在以下问题:

### ISSUE THREAD

**Issue by 592530326** [kxg3030/shermie-proxy#9]
经过测试,我发现,OnSocket5RequestEvent(这里获取到的数据,其实是服务器返回来的数据)和OnSocket5ResponseEvent(这里获取到的数据,其实是客户端发送的数据),而且无法进行数据包拦截

**Comment by kxg3030** [comment]
好的 这个问题我修复一下 数据也可以支持修改
